# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 12:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('billboard_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 20, 12, 43, 20, 126926, tzinfo=utc)),
        ),
    ]
